; PlatformIO Project Configuration File

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
upload_speed = 115200
monitor_speed = 115200

; ==== CẤU HÌNH BỘ NHỚ & TỐI ƯU AI ====
board_build.partitions = min_spiffs.csv
build_unflags = -Os        ; Tắt chế độ tối ưu dung lượng
build_flags = -O3          ; Bật tối ưu tốc độ AI tối đa

; ==== DANH SÁCH THƯ VIỆN ====
lib_deps =
    mobizt/Firebase Arduino Client Library for ESP8266 and ESP32 @ ^4.4.14
    sparkfun/SparkFun MAX3010x Pulse and Proximity Sensor Library @ ^1.1.2
    tockn/MPU6050_tockn @ ^1.5.2
    adafruit/Adafruit MLX90614 Library @ ^2.1.5
    mikalhart/TinyGPSPlus @ ^1.0.3
    plerup/EspSoftwareSerial @ ^8.1.0
    adafruit/Adafruit GFX Library @ ^1.11.9
    adafruit/Adafruit ST7735 and ST7789 Library @ ^1.10.3
    tzapu/WiFiManager @ ^2.0.16-rc.2
    arduino-libraries/Arduino_JSON @ ^0.2.0
    ricmoo/QRCode @ ^0.0.1

; ==== MÔI TRƯỜNG NẠP CODE TỪ XA (OTA) ====
[env:esp32dev_ota]
platform = espressif32
board = esp32dev
framework = arduino
board_build.partitions = min_spiffs.csv
build_unflags = -Os
build_flags = -O3
lib_deps = ${env:esp32dev.lib_deps}

; -- Khai báo cấu hình OTA --
upload_protocol = espota
; IP của ESP32 hoặc Hostname (mDNS)
; Hãy thay đổi dòng này thành IP thực tế của ESP32 nếu 'DAKT1-ESP32-AI.local' không hoạt động trên máy bạn (ví dụ: upload_port = 192.168.1.100)
upload_port = 192.168.7.185